name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
- type: input
  id: bug_summary
  attributes:
    label: Bug Summary
    validations:
      required: true
- type: markdown
  id: detailed_description
  attributes:
    label: Detailed Description
    validations:
      required: true
- type: markdown
  id: current_behavior
  attributes:
    label: Current Behavior
    validations:
      required: false
- type: markdown
  id: expected_behavior
  attributes:
    label: Expected Behavior
    validations:
      required: false
- type: markdown
  id: reproduction_steps
  attributes:
    label: Steps to Reproduce
    value: |
      1.
      2.
      3.
    validations:
      required: false
