name: Bug Report
description: File a bug report
title: "[Feature]: "
labels: ["enhancement"]
assignees:
body:
  - type: input
    attributes:
      label: Feature Summary
      value:
      validations:
        required: true
  - type: markdown
    attributes:
      label: Detailed Description
      value:
      validations:
        required: true
