name: Lint, Build, Test

on: 
  pull_request:
    branches: [ main ]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.13.2 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          config: baseUrl=http://localhost:1337
      -run: npm run lint
